#!/usr/bin/env python
"""Generate web/sample.js -- a redacted real crash report for the web demo.

Source: tests/fixtures/ground-truth/crash-2026-09-08_22.42.32-server.txt
(279 KB, the watchdog/hang report that attributes lithium at 97%). Kept
sections: header + exception chain, the Head stacktrace, and System Details
(with the Mod List -- that is what makes attribution strong). Dropped: the
repeated full trace sections that pad crash reports to hundreds of KB.

Redaction reuses tools/harvest_corpus.redact (the same function that scrubs
the committed corpus index), then a path-scrub pass for anything it misses.

Run: python tools/make_web_sample.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

from harvest_corpus import redact  # noqa: E402

SRC = ROOT / "tests" / "fixtures" / "ground-truth" / "crash-2026-09-08_22.42.32-server.txt"
OUT = ROOT / "web" / "sample.js"

KEEP_SECTIONS = ("System Details",)


def extract(text: str) -> str:
    """Header + first stacktrace + System Details; drop repeated traces."""
    # everything up to the first section marker = banner + exception chain
    first_sec = re.search(r"^-- .+ --$", text, re.M)
    head = text[: first_sec.start()] if first_sec else text[:6000]

    parts = [head.rstrip()]

    # System Details section (contains the Mod List -> attribution signal)
    for name in KEEP_SECTIONS:
        m = re.search(rf"^-- {re.escape(name)} --$", text, re.M)
        if not m:
            continue
        nxt = re.search(r"^-- .+ --$", text[m.end():], re.M)
        end = m.end() + nxt.start() if nxt else len(text)
        parts.append(text[m.start():end].rstrip())

    return "\n\n".join(parts)


def scrub_paths(text: str) -> str:
    """Belt-and-braces: no absolute paths, no usernames, no drive letters."""
    text = re.sub(r"[A-Za-z]:[\\/][^\s\"']*", "<PATH>", text)
    text = re.sub(r"/(?:home|Users)/[^\s\"']+", "<PATH>", text)
    text = re.sub(r"\\\\[A-Za-z0-9_.\\-]+\\\\[^\s\"']*", "<PATH>", text)
    return text


def main() -> int:
    raw = SRC.read_text(encoding="utf-8", errors="replace")
    sample = scrub_paths(redact(extract(raw)))

    # guard: nothing user-identifying may survive into a PUBLIC repo file
    leaks = []
    for pat, why in [
        (r"Administrator", "windows username"),
        (r"\b\d{1,3}(?:\.\d{1,3}){3}\b", "possible IPv4"),
        (r"[A-Za-z]:[\\/]", "drive path"),
    ]:
        for m in re.finditer(pat, sample):
            ctx = sample[max(0, m.start() - 40): m.end() + 20]
            # mod version strings like 10.4.5.19 legitimately look like IPv4
            if why == "possible IPv4" and re.search(
                    r"[\w\-]+\d*\.\d+\.\d+\.\d+", ctx):
                continue
            leaks.append((why, m.group(0), ctx.replace("\n", " ")[:80]))
    if leaks:
        print("REDACTION LEAKS -- refusing to write:")
        for w, g, c in leaks[:10]:
            print(f"  [{w}] {g!r} in ...{c}...")
        return 1

    js = (
        "// Generated by tools/make_web_sample.py -- DO NOT EDIT BY HAND.\n"
        "// Redacted real crash report (watchdog hang, lithium 97%) used by the\n"
        "// web app's \"Try a real report\" button. Source fixture is MIT-committed\n"
        "// ground truth; this derivative adds a path scrub + the corpus redactor.\n"
        "window.MCD_SAMPLE = " + json.dumps(sample, ensure_ascii=False) + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(js)} bytes "
          f"(sample {len(sample)} chars, from {len(raw)} char source)")

    # logic check: the generated sample must diagnose as expected
    from mcd.cli import diagnose
    rep, findings, t = diagnose(None, sample, source="<web-sample>")
    ids = sorted({f.rule_id for f in findings})
    sus = [s.modid for s in t.suspects]
    ok = "hang.watchdog" in ids and "lithium" in sus
    print(f"diagnosis check: findings={ids} suspects={sus[:3]} -> "
          f"{'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
